name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm run install-all
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run environment
      run: npm run dev
      env:
        MONGOOSE_CONNECTION_STRING: ${{ secrets.MONGOOSE_CONNECTION_STRING }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Wait on
      uses: iFaxity/wait-on-action@v1.2.1
      with:
        resource: http://localhost:3001
    - name: Run Playwright tests
      working-directory: ./Tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
